name = "DetectingShapes"
uuid = "d4c3e3b0-7a3f-4f2b-9a5c-0f2b7e6a1234"
version = "0.1.0"
authors = ["Eliot Morin"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
CSV = "0.10.15"
Clustering = "0.15.8"
DataFrames = "1.8.1"
Distances = "0.10.12"
PlotlyJS = "0.18.17"
Plots = "1.41.3"
StatsPlots = "0.15.8"
