name = "DetectingShapes"
uuid = "d4c3e3b0-7a3f-4f2b-9a5c-0f2b7e6a1234"
version = "0.1.0"
authors = ["Eliot Morin"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
LinearAlgebra = "1.12.0"
PlotlyJS = "0.18.17"
Plots = "1.41.3"
